site_name: PixelStudio
theme:
  name: material
nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quick-start.md
      - Building: getting-started/building.md
  - User Guide:
      - Interface: user-guide/interface.md
      - Drawing Tools: user-guide/drawing-tools.md
      - Layers: user-guide/layers.md
      - Animation: user-guide/animation.md
      - Palettes: user-guide/palettes.md
      - Exporting: user-guide/exporting.md
      - Shortcuts: user-guide/shortcuts.md
  - Development:
      - Architecture: development/architecture.md
      - Project Structure: development/project-structure.md
      - Coding Standards: development/coding-standards.md
      - Contributing: development/contributing.md
  - Features:
      - Drawing System: features/drawing-system.md
      - Layer Management: features/layer-management.md
      - Animation Timeline: features/animation-timeline.md
      - File Formats: features/file-formats.md
  - About:
      - Roadmap: about/roadmap.md
      - License: about/license.md
      - Changelog: about/changelog.md